import { ITask } from './Contracts/ITask';
export const TASKS: ITask[] = [
  {
    id: 1,
    status: 'completed',
    content: 'Task 1',
    important: false,
    created_at: new Date(2020, 0, 1, 9, 0),
    updated_at: new Date(2020, 0, 1, 9, 0),
  },
  {
    id: 2,
    status: 'completed',
    content: 'Task 2',
    important: false,
    created_at: new Date(2020, 0, 1, 9, 0),
    updated_at: new Date(2020, 0, 1, 9, 0),
  },
  {
    id: 3,
    status: 'completed',
    content: 'Task 3',
    important: false,
    created_at: new Date(2020, 0, 1, 9, 0),
    updated_at: new Date(2020, 0, 1, 9, 0),
  },
  {
    id: 4,
    status: 'completed',
    content: 'Task 4',
    important: false,
    created_at: new Date(2020, 0, 1, 9, 0),
    updated_at: new Date(2020, 0, 1, 9, 0),
  },
  {
    id: 5,
    status: 'pending',
    content: 'Task 5',
    important: false,
    created_at: new Date(2020, 0, 1, 9, 0),
    updated_at: new Date(2020, 0, 1, 9, 0),
  },
  {
    id: 6,
    status: 'pending',
    content: 'Task 6',
    important: false,
    created_at: new Date(2020, 0, 1, 9, 0),
    updated_at: new Date(2020, 0, 1, 9, 0),
  },
  {
    id: 7,
    status: 'pending',
    content: 'Task 7',
    important: false,
    created_at: new Date(2020, 0, 1, 9, 0),
    updated_at: new Date(2020, 0, 1, 9, 0),
  },
];
